### ISSUE TITLE
Issue watchlist for upcoming Kit releases

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse#243]
This issue keeps tracks of things we're watching out for as new versions of Kit are released

* [x] Dynamic Texture Provider: https://github.com/CesiumGS/cesium-omniverse/issues/116
  * Fixed in Create 2022.3.3
  * Console warnings fixed in pre-release (4/22/2023)
* [x] Dynamic texcoords - for mesh pool
  * Fixed in pre-release (4/22/2023)
* [x] Orphaned prims: https://github.com/CesiumGS/cesium-omniverse/issues/214
  * Fixed in pre-release (3/28/2023)
* [x] Dynamic material support in Fabric: https://github.com/CesiumGS/cesium-omniverse/issues/242
  * `materialId` assignment fixed in pre-release (3/28/2023)
  * Dynamic material values are expected in Kit 105
* [x] Simplify prim deletion by removing [`/TempChangeTracking`](https://github.com/CesiumGS/cesium-omniverse/blob/0b2499e7faff26dbb357b0260af901e84c721254/src/core/src/FabricStageUtil.cpp#L934-L972) workaround
  * Not fixed as of pre-release (3/28/2023)
* [ ] USDRT material support and switch away from using Fabric directly.
  * Related: https://github.com/CesiumGS/cesium-omniverse/issues/94
* [x] Dynamic skies support in Fabric
  * Dragging in a sky works in Create 2022.3.3
  * Subsequent adjustments to time of day do not work (expected in Kit 105)
* [x] Fabric geometry doesn't become ready until camera stops moving: https://github.com/CesiumGS/cesium-omniverse/issues/255
  * [x] Fixed in pre-release (4/22/2023)
* [ ] Physics support in Fabric: https://github.com/CesiumGS/cesium-omniverse/issues/153
* [ ] Intermittent crashes and hangs (issue TBD)
* [x] `main` crashes in Linux in pre-release (5/1/2023)
* [ ] Custom materials don't get populated correctly when Fabric is enabled by default: https://github.com/CesiumGS/cesium-omniverse/pull/406
* [ ] Compressed texture fixes in Kit 105.1
* [ ] When custom material is saved `cesium.mdl` is converted to `./cesium.mdl`
* [ ] pipapi improvements: https://github.com/CesiumGS/cesium-omniverse/pull/383
